language: python
sudo: required
dist: xenial
python: "3.7"

script:
  - echo Nothing happens here

after_script: # implicit pytest result here is skipped (as is in after_deploy)
  - if ! pytest; travis_terminate 1; fi